import {combineReducers} from 'redux';
import CUSTOM_VALUE_TO_STORE from './CUSTOM_VALUE_TO_STORE.jsx';
import INITIAL_VALUE_TO_STORE from './INITIAL_VALUE_TO_STORE.jsx';
import MEASUREMENTS from './MEASUREMENTS.jsx';
import CHANGE_TYPE_OF_GROUP_OF_MEASUREMENTS from './CHANGE_TYPE_OF_GROUP_OF_MEASUREMENTS.jsx';
import CHANGE_TYPE_OF_MEASUREMENTS from './CHANGE_TYPE_OF_MEASUREMENTS.jsx';
import CREATE_CALC_ARRAY from './CREATE_CALC_ARRAY.jsx';

export default combineReducers({
    CUSTOM_VALUE_TO_STORE,
    INITIAL_VALUE_TO_STORE,
    MEASUREMENTS,
    CHANGE_TYPE_OF_GROUP_OF_MEASUREMENTS,
    CHANGE_TYPE_OF_MEASUREMENTS,
    CREATE_CALC_ARRAY
})